package main

import (
	"fmt"
	"log/slog"
	"os"
	"sort"
	"strings"

	"callmemaybe/internal/policy"
	"callmemaybe/internal/render"
)

// The trunk side of the CLI: which providers this box registers with, which
// line's number arrives on which of them, and — the part worth reading twice —
// which one an emergency call leaves by.
//
// Everything here is silent on an install with no trunks.toml. That is the
// compatibility gate for the whole milestone: one provider, one registration,
// a hand-written pjsip.conf, and nobody has to read the word "trunk" to check
// their config.

func trunksPathArg(explicit string) string {
	if explicit != "" {
		return explicit
	}
	if p := os.Getenv("TRUNKS_PATH"); p != "" {
		return p
	}
	return "./trunks.toml"
}

// ── doorman check: the trunk inventory ───────────────────────────────────

// printTrunks reports the provider inventory and which lines land on it.
// Nothing is printed when there is no trunks.toml.
func printTrunks(trunks *policy.Trunks, results []checkedLine) {
	if !trunks.Present() {
		return
	}

	// Which lines each trunk carries, and which lines named a trunk that has
	// no number to route — a real state, and one nothing else would mention.
	carried := map[string][]string{}
	var numberless []string
	for _, r := range results {
		if r.err != nil {
			continue
		}
		line := r.pol.Line()
		if line.Trunk == "" {
			continue
		}
		carried[line.Trunk] = append(carried[line.Trunk], r.Name)
		if line.Number == "" {
			numberless = append(numberless, r.Name)
		}
	}

	fmt.Printf("\nTrunks: %d   (%s)\n\n", trunks.Len(), trunks.Where())
	width := len("id")
	for _, tr := range trunks.All() {
		if len(tr.ID) > width {
			width = len(tr.ID)
		}
	}
	fmt.Printf("  %-*s  %-14s %-24s %s\n", width, "id", "provider", "host", "lines")
	for _, tr := range trunks.All() {
		lines := "(none yet)"
		if names := carried[tr.ID]; len(names) > 0 {
			sort.Strings(names)
			lines = strings.Join(names, ", ")
		}
		fmt.Printf("  %-*s  %-14s %-24s %s\n", width, tr.ID,
			orDefault(tr.Provider, "—"), tr.Host, lines)
	}

	fmt.Println("\n  Each trunk registers outbound and inbound calls arrive back down that")
	fmt.Println("  registration. `doorman render` writes line=yes and endpoint=<id> on every")
	fmt.Println("  one, which is what binds inbound traffic to the endpoint — no identify")
	fmt.Println("  block, no provider IP allow-list, no port forward.")

	fmt.Println("\n  Generated by `doorman render`, and never hand-edited:")
	fmt.Println("    pjsip_trunks.conf        registrations (real passwords — never commit)")
	fmt.Println("    extensions_trunks.conf   one inbound context per trunk, one route per DID")

	// A DID route needs both halves. Saying so here is cheaper than an
	// operator discovering it from a call that reached the wrong greeting.
	if len(numberless) > 0 {
		sort.Strings(numberless)
		fmt.Printf("\n  No DID route generated for: %s\n", strings.Join(numberless, ", "))
		fmt.Println("    A route needs [line] trunk and [line] number together. These lines")
		fmt.Println("    name a trunk but no number, so calls for them fall through to the")
		fmt.Println("    default line. Add [line] number, or route them by hand.")
	}
}

// ── doorman check: the emergency trunk ───────────────────────────────────

// printEmergency says which trunk carries 911, and whether that was chosen or
// inferred.
//
// The plan asks for this by name and it is worth restating why: requiring an
// explicit designation creates a state where somebody forgot and 911 has no
// route, and defaulting silently creates one where somebody is surprised.
// Defaulting *and* announcing is the only arrangement with neither failure.
//
// It is also honest about today. Outbound routing by trunk is not built, so
// this says where 911 *will* leave by rather than implying it already does.
func printEmergency(trunks *policy.Trunks, results []checkedLine) {
	if !trunks.Present() {
		return
	}

	primary := ""
	if results[0].err == nil {
		primary = results[0].pol.Line().Trunk
	}
	id, chosen := trunks.Emergency(primary)

	fmt.Println("\nEmergency calls")
	fmt.Println()
	switch {
	case id == "":
		fmt.Println("  911 would leave by   (undecided)")
		fmt.Println()
		fmt.Println("  Settle this. Nothing is designated and plain policy.toml names no")
		fmt.Println("  trunk, so there is no answer to which provider carries an emergency")
		fmt.Println("  call. Set emergency_trunk in trunks.toml, or give policy.toml a")
		fmt.Println("  [line] trunk — the primary line is the default for everything")
		fmt.Println("  unqualified, and this is the most important thing it defaults.")
		fmt.Println()
		fmt.Println("  Not an error today only because outbound routing by trunk is not")
		fmt.Println("  built yet: 911 still leaves by the dialplan's _911 line, which has")
		fmt.Println("  one trunk hard-coded in it. It becomes an error when that changes.")
		fmt.Println()
		fmt.Println("  Deliberately not \"the only trunk you declared\" and not \"the first\":")
		fmt.Println("  a default derived from file order moves silently the day a second")
		fmt.Println("  block is added above it, and this is the one route where a silent")
		fmt.Println("  move is unacceptable.")
	case chosen:
		fmt.Printf("  911 would leave by   %s   (chosen — emergency_trunk in %s)\n", id, trunks.Where())
	default:
		fmt.Printf("  911 would leave by   %s   (inferred — the primary line's trunk, from policy.toml)\n", id)
	}

	if id != "" {
		tr, known := trunks.Lookup(id)
		if !known {
			// Only reachable through an inferred id: emergency_trunk itself is
			// validated at load, but policy.toml's trunk is validated against
			// the inventory only when one is in play.
			fmt.Printf("\n  ✗ %q is not a trunk declared in %s.\n", id, trunks.Where())
			return
		}
		fmt.Printf("  provider             %s\n", orDefault(tr.Provider, "(unnamed)"))
		fmt.Printf("  registered address   %s\n", describeE911(tr))
	}

	fmt.Println("\n  E911 is registered per DID against a street address, so the trunk that")
	fmt.Println("  carries 911 must be the one whose address is on file — not whichever")
	fmt.Println("  line a caller happens to be on, which nobody grabbing the nearest")
	fmt.Println("  handset knows anyway.")
	fmt.Println()
	fmt.Println("  Not yet enforced: outbound routing by trunk is not built, so today an")
	fmt.Println("  emergency call still leaves by whatever the dialplan's _911 line says.")
	fmt.Println("  This is what that will read.")
	fmt.Println()
	fmt.Println("  And the honest framing: this is a supplementary phone. It stops working")
	fmt.Println("  in a power cut and on a bad internet day. Nobody should make it a")
	fmt.Println("  household's only route to emergency services.")
}

func describeE911(tr policy.Trunk) string {
	switch {
	case tr.E911 == nil:
		return "unknown — set e911 = true|false on this trunk once you have checked"
	case *tr.E911:
		return "declared (e911 = true)"
	default:
		return "✗ declared ABSENT (e911 = false) — this trunk cannot call for help"
	}
}

// ── startup ──────────────────────────────────────────────────────────────

// announceEmergencyTrunk says which trunk carries 911, every boot.
//
// Same reasoning as announceOutbound: a default nobody announces is a default
// somebody is surprised by, and this is the one worth being surprised by
// least. Silent when there is no trunks.toml, because then there is one trunk
// and no decision to announce.
func announceEmergencyTrunk(trunks *policy.Trunks, primaryLineTrunk string, log *slog.Logger) {
	if !trunks.Present() {
		return
	}
	id, chosen := trunks.Emergency(primaryLineTrunk)
	how := "inferred from the primary line"
	if chosen {
		how = "chosen"
	}
	if id == "" {
		log.Warn("no trunk carries emergency calls",
			"hint", "set emergency_trunk in trunks.toml, or [line] trunk in policy.toml")
		return
	}
	tr, known := trunks.Lookup(id)
	if !known {
		log.Warn("the emergency trunk is not declared in the trunk inventory",
			"trunk", id, "how", how, "known", strings.Join(trunks.IDs(), ", "))
		return
	}
	log.Info("emergency trunk", "trunk", id, "how", how,
		"provider", tr.Provider, "registeredAddress", e911Field(tr),
		"hint", "outbound routing by trunk is not built yet — 911 leaves by the dialplan's _911 line")
}

func e911Field(tr policy.Trunk) string {
	if tr.E911 == nil {
		return "unknown"
	}
	if *tr.E911 {
		return "declared"
	}
	return "declared absent"
}

// ── doorman render ───────────────────────────────────────────────────────

// renderTrunkLines is what the trunk dialplan needs from the policy files: one
// entry per line, with the DID it answers and the provider that DID arrives
// on. Order is DiscoverLines' order — the primary line first — so the
// generated file reads the same way twice running.
func renderTrunkLines(ids []lineIdentity) []render.TrunkLine {
	out := make([]render.TrunkLine, 0, len(ids))
	for _, id := range ids {
		out = append(out, render.TrunkLine{
			Name:   id.Name,
			Label:  id.Label,
			Number: id.Number,
			Trunk:  id.Trunk,
		})
	}
	return out
}
