package main

import (
	"fmt"
	"log/slog"
	"os"
	"sort"
	"strings"

	"callmemaybe/internal/policy"
	"callmemaybe/internal/render"
)

// The trunk side of the CLI: which providers this box registers with, which
// line's number arrives on which of them, and — the part worth reading twice —
// which one an emergency call leaves by.
//
// Everything here is silent on an install with no trunks.toml. That is the
// compatibility gate for the whole milestone: one provider, one registration,
// a hand-written pjsip.conf, and nobody has to read the word "trunk" to check
// their config.

func trunksPathArg(explicit string) string {
	if explicit != "" {
		return explicit
	}
	if p := os.Getenv("TRUNKS_PATH"); p != "" {
		return p
	}
	return "./trunks.toml"
}

// ── doorman check: the trunk inventory ───────────────────────────────────

// printTrunks reports the provider inventory and which lines land on it.
// Nothing is printed when there is no trunks.toml.
func printTrunks(trunks *policy.Trunks, results []checkedLine) {
	if !trunks.Present() {
		return
	}

	// Which lines each trunk carries, and which lines named a trunk that has
	// no number to route — a real state, and one nothing else would mention.
	carried := map[string][]string{}
	var numberless []string
	for _, r := range results {
		if r.err != nil {
			continue
		}
		line := r.pol.Line()
		if line.Trunk == "" {
			continue
		}
		carried[line.Trunk] = append(carried[line.Trunk], r.Name)
		if line.Number == "" {
			numberless = append(numberless, r.Name)
		}
	}

	fmt.Printf("\nTrunks: %d   (%s)\n\n", trunks.Len(), trunks.Where())
	width := len("id")
	for _, tr := range trunks.All() {
		if len(tr.ID) > width {
			width = len(tr.ID)
		}
	}
	fmt.Printf("  %-*s  %-14s %-24s %s\n", width, "id", "provider", "host", "lines")
	for _, tr := range trunks.All() {
		lines := "(none yet)"
		if names := carried[tr.ID]; len(names) > 0 {
			sort.Strings(names)
			lines = strings.Join(names, ", ")
		}
		fmt.Printf("  %-*s  %-14s %-24s %s\n", width, tr.ID,
			orDefault(tr.Provider, "—"), tr.Host, lines)
	}

	fmt.Println("\n  Each trunk registers outbound and inbound calls arrive back down that")
	fmt.Println("  registration. `doorman render` writes line=yes and endpoint=<id> on every")
	fmt.Println("  one, which is what binds inbound traffic to the endpoint — no identify")
	fmt.Println("  block, no provider IP allow-list, no port forward.")

	fmt.Println("\n  Generated by `doorman render`, and never hand-edited:")
	fmt.Println("    pjsip_trunks.conf        registrations (real passwords — never commit)")
	fmt.Println("    extensions_trunks.conf   one inbound context per trunk, one route per DID")

	// A DID route needs both halves. Saying so here is cheaper than an
	// operator discovering it from a call that reached the wrong greeting.
	if len(numberless) > 0 {
		sort.Strings(numberless)
		fmt.Printf("\n  No DID route generated for: %s\n", strings.Join(numberless, ", "))
		fmt.Println("    A route needs [line] trunk and [line] number together. These lines")
		fmt.Println("    name a trunk but no number, so calls for them fall through to the")
		fmt.Println("    default line. Add [line] number, or route them by hand.")
	}
}

// ── doorman check: the emergency trunk ───────────────────────────────────

// printEmergency says which trunk carries 911, whether that was chosen or
// inferred, and what happens when it is down. It returns false when there is no
// answer, which is the one configuration this command refuses outright.
//
// The plan asks for this by name and it is worth restating why: requiring an
// explicit designation creates a state where somebody forgot and 911 has no
// route, and defaulting silently creates one where somebody is surprised.
// Defaulting *and* announcing is the only arrangement with neither failure.
func printEmergency(trunks *policy.Trunks, results []checkedLine) bool {
	if !trunks.Present() {
		return true
	}

	primary := ""
	if results[0].err == nil {
		primary = results[0].pol.Line().Trunk
	}
	id, chosen := trunks.Emergency(primary)

	fmt.Println("\nEmergency calls")
	fmt.Println()
	switch {
	case id == "":
		fmt.Println("✗ 911 leaves by       (undecided)")
		fmt.Println()
		fmt.Println("  Settle this. Nothing is designated and plain policy.toml names no")
		fmt.Println("  trunk, so there is no answer to which provider carries an emergency")
		fmt.Println("  call. Set emergency_trunk in trunks.toml, or give policy.toml a")
		fmt.Println("  [line] trunk — the primary line is the default for everything")
		fmt.Println("  unqualified, and this is the most important thing it defaults.")
		fmt.Println()
		fmt.Println("  `doorman render` refuses to generate until this has an answer. With")
		fmt.Println("  one provider there was nothing to choose; with several, a dialplan")
		fmt.Println("  that routes every DID beautifully and says nothing about 911 is worse")
		fmt.Println("  than no generated dialplan at all.")
		fmt.Println()
		fmt.Println("  Deliberately not \"the only trunk you declared\" and not \"the first\":")
		fmt.Println("  a default derived from file order moves silently the day a second")
		fmt.Println("  block is added above it, and this is the one route where a silent")
		fmt.Println("  move is unacceptable.")
		return false
	case chosen:
		fmt.Printf("  911 leaves by        %s   (chosen — emergency_trunk in %s)\n", id, trunks.Where())
	default:
		fmt.Printf("  911 leaves by        %s   (inferred — the primary line's trunk, from policy.toml)\n", id)
	}

	tr, known := trunks.Lookup(id)
	if !known {
		// Only reachable through an inferred id: emergency_trunk itself is
		// validated at load, but policy.toml's trunk is validated against
		// the inventory only when one is in play.
		fmt.Printf("\n✗ %q is not a trunk declared in %s.\n", id, trunks.Where())
		return false
	}
	fmt.Printf("  provider             %s\n", orDefault(tr.Provider, "(unnamed)"))
	fmt.Printf("  registered address   %s\n", describeE911(tr))

	if fallbacks := emergencyFallbacks(trunks, id); len(fallbacks) > 0 {
		fmt.Printf("  falls over to        %s\n", strings.Join(fallbacks, ", then "))
		fmt.Println()
		fmt.Println("  If the designated trunk cannot carry the call, the next one is tried,")
		fmt.Println("  and the dispatcher may then see the wrong address. That is a deliberate")
		fmt.Println("  trade: a connected call lets a human say their address out loud, and a")
		fmt.Println("  failed call gives them nothing. Connection first. The order puts the")
		fmt.Println("  trunks that declare a registered address ahead of the ones that do not.")
	} else {
		fmt.Println()
		fmt.Println("  One trunk, so nothing to fall over to: if it cannot carry the call,")
		fmt.Println("  the caller hears congestion and needs another phone.")
	}

	fmt.Println()
	fmt.Println("  Generated into extensions_trunks.conf as [cmm-emergency] and reached")
	fmt.Println("  from _911 in [internal]. Confirm what Asterisk actually loaded:")
	fmt.Println("    sudo asterisk -rx 'dialplan show cmm-emergency'")
	fmt.Println("  No context there means the file is not #included and 911 is leaving by")
	fmt.Println("  the dialplan's DEFAULT_TRUNK. See RUNBOOK, \"Which trunk carries 911\".")

	fmt.Println("\n  E911 is registered per DID against a street address, so the trunk that")
	fmt.Println("  carries 911 must be the one whose address is on file — not whichever")
	fmt.Println("  line a caller happens to be on, which nobody grabbing the nearest")
	fmt.Println("  handset knows anyway. An emergency call never presents a line's")
	fmt.Println("  outbound_cid, on any path.")
	fmt.Println()
	fmt.Println("  Not every provider offers E911 in every area, and a provider without it")
	fmt.Println("  is a phone that cannot call for help. That is a reason to reject the")
	fmt.Println("  provider, not a line item to skip.")
	fmt.Println()
	fmt.Println("  And the honest framing: this is a supplementary phone. It stops working")
	fmt.Println("  in a power cut and on a bad internet day. Nobody should make it a")
	fmt.Println("  household's only route to emergency services.")
	return true
}

// emergencyFallbacks is the order 911 tries the other trunks in, mirroring what
// `doorman render` generates. Derived from the same inventory rather than read
// back out of the generated file, so `doorman check` can say it before anything
// has been rendered.
func emergencyFallbacks(trunks *policy.Trunks, designated string) []string {
	frags := render.EmergencyOrder(trunks.All(), designated)
	out := make([]string, 0, len(frags))
	for _, tr := range frags {
		if tr.ID != designated {
			out = append(out, tr.ID)
		}
	}
	return out
}

func describeE911(tr policy.Trunk) string {
	switch {
	case tr.E911 == nil:
		return "unknown — set e911 = true|false on this trunk once you have checked"
	case *tr.E911:
		return "declared (e911 = true)"
	default:
		return "✗ declared ABSENT (e911 = false) — this trunk cannot call for help"
	}
}

// ── startup ──────────────────────────────────────────────────────────────

// announceEmergencyTrunk says which trunk carries 911, every boot.
//
// Same reasoning as announceOutbound: a default nobody announces is a default
// somebody is surprised by, and this is the one worth being surprised by
// least. Silent when there is no trunks.toml, because then there is one trunk
// and no decision to announce.
func announceEmergencyTrunk(trunks *policy.Trunks, primaryLineTrunk string, log *slog.Logger) {
	if !trunks.Present() {
		return
	}
	id, chosen := trunks.Emergency(primaryLineTrunk)
	how := "inferred from the primary line"
	if chosen {
		how = "chosen"
	}
	if id == "" {
		log.Error("no trunk carries emergency calls",
			"hint", "set emergency_trunk in trunks.toml, or [line] trunk in policy.toml — "+
				"`doorman render` refuses to generate a dialplan until this has an answer")
		return
	}
	tr, known := trunks.Lookup(id)
	if !known {
		log.Warn("the emergency trunk is not declared in the trunk inventory",
			"trunk", id, "how", how, "known", strings.Join(trunks.IDs(), ", "))
		return
	}
	log.Info("emergency trunk", "trunk", id, "how", how,
		"provider", tr.Provider, "registeredAddress", e911Field(tr),
		"fallsOverTo", orDefault(strings.Join(emergencyFallbacks(trunks, id), ", "), "(nothing — one trunk)"),
		"hint", "911 is routed by the generated [cmm-emergency] context, not by doorman — "+
			"confirm with: asterisk -rx 'dialplan show cmm-emergency'")
}

func e911Field(tr policy.Trunk) string {
	if tr.E911 == nil {
		return "unknown"
	}
	if *tr.E911 {
		return "declared"
	}
	return "declared absent"
}

// ── doorman render ───────────────────────────────────────────────────────

// resolveEmergency answers which trunk 911 leaves by, for the generator.
//
// The rule lives here rather than in `internal/render` because it spans two
// files: emergency_trunk in trunks.toml wins, and unset it is the primary
// line's [line] trunk — plain policy.toml, already the default for everything
// unqualified. Resolved once, in the same process that prints it, so the
// generated dialplan and `doorman check` can never disagree about it.
//
// A missing policy.toml leaves the primary line's trunk empty, which is a real
// state: `doorman render` deliberately works before the rules exist. With a
// trunks.toml in play it means emergency_trunk has to be set, and render says
// so rather than generating a dialplan that has no answer for 911.
func resolveEmergency(trunks *policy.Trunks, ids []lineIdentity) render.Emergency {
	primary := ""
	for _, id := range ids {
		if id.Name == policy.DefaultLine {
			primary = id.Trunk
			break
		}
	}
	trunk, chosen := trunks.Emergency(primary)
	return render.Emergency{Trunk: trunk, Chosen: chosen}
}

// renderTrunkLines is what the trunk dialplan needs from the policy files: one
// entry per line, with the DID it answers and the provider that DID arrives
// on. Order is DiscoverLines' order — the primary line first — so the
// generated file reads the same way twice running.
func renderTrunkLines(ids []lineIdentity) []render.TrunkLine {
	out := make([]render.TrunkLine, 0, len(ids))
	for _, id := range ids {
		out = append(out, render.TrunkLine{
			Name:   id.Name,
			Label:  id.Label,
			Number: id.Number,
			Trunk:  id.Trunk,
		})
	}
	return out
}
