// Package render generates the per-handset Asterisk configuration from
// handsets.toml, making the inventory file the single source of truth.
// Before this existed, adding a phone meant hand-editing three places that
// had to agree (PJSIP blocks, dialplan numbers/hints, the policy handset
// list) — the most error-prone procedure in the runbook. Now it is one file
// and one command.
//
// Only the repetitive per-phone material is generated. The trunk, transports,
// ARI, and feature dialplan stay hand-authored: they are written once and
// carry judgement; the handset blocks are written N times and carry none.
package render

import (
	"fmt"
	"sort"
	"strings"

	"callmemaybe/internal/policy"
)

// Env resolves a secret by name — process environment layered over .env.
type Env func(key string) (string, bool)

// Fragments holds the generated file contents.
type Fragments struct {
	// PJSIP is the endpoint/auth/aor blocks — pjsip_handsets.conf.
	PJSIP string
	// Dialplan is the [handsets-internal] context (numbers, hints, ring-all,
	// page-all) — extensions_handsets.conf.
	Dialplan string
	// Generated counts the PJSIP handsets rendered; pseudo-handsets
	// (Local/... endpoints) are listed in the map but not generated.
	Generated int
}

// header is the banner every generated file carries. from names the source of
// truth so the fix — edit that, re-render — is on the screen of whoever opened
// the wrong file. secrets adds the line that matters for the PJSIP fragments:
// they hold real passwords, and a generated file is the one somebody assumes
// is safe to paste into an issue.
func header(from string, secrets bool) string {
	var b strings.Builder
	b.WriteString("; ══════════════════════════════════════════════════════════════\n")
	fmt.Fprintf(&b, "; GENERATED by \"doorman render\" from %s — DO NOT EDIT.\n", from)
	fmt.Fprintf(&b, "; Hand edits are lost on the next render; change %s instead.\n", from)
	if secrets {
		b.WriteString("; THIS FILE CONTAINS REAL SIP PASSWORDS. Install it root-owned and\n")
		b.WriteString("; mode 0640, and never commit it — not to a private repo either.\n")
	}
	b.WriteString("; ══════════════════════════════════════════════════════════════\n\n")
	return b.String()
}

// The two channel variables the dialplan reads to place an outbound call: what
// it presents, and which provider it leaves by. Each name appears in exactly
// three places and they have to agree: here, internal/lobby/console.go, and
// the shared [cmm-outbound] context in asterisk/extensions.conf. There is no
// shared constant because the third of those is not Go — the same arrangement
// "voicemail-drop" has always had.
const (
	outboundCIDVar   = "OUTBOUND_CID"
	outboundTrunkVar = "OUTBOUND_TRUNK"
)

// OutboundIdentity is what one handset presents and where its calls leave by.
//
// The two travel together in one value on purpose. A provider will not let you
// present a number its account does not own — it rejects the call or silently
// rewrites the caller ID as anti-spoofing — so the caller ID and the trunk are
// one decision, not two settings that happen to sit near each other. Two maps
// could disagree; a pair cannot.
type OutboundIdentity struct {
	// CID is what the callee sees, in E.164, or "" for whatever the trunk
	// sends — which is what every outbound call did before lines existed.
	CID string
	// Trunk is the PJSIP endpoint the call leaves by: a trunks.toml id. Empty
	// means the dialplan's DEFAULT_TRUNK decides, which is every install with
	// one provider and no trunks.toml at all.
	Trunk string
}

// set reports whether this handset has any outbound identity to write.
func (o OutboundIdentity) set() bool { return o.CID != "" || o.Trunk != "" }

// Build renders both fragments. Secrets come exclusively through env — the
// generated PJSIP file contains real passwords and must be treated like
// pjsip.conf itself (root-owned, mode 0640, never committed).
//
// outbound maps handset id to the identity that phone calls with — the caller
// ID it presents and the trunk it leaves by — resolved from [line]
// outbound_cid, [line] trunk and [line] outbound_handsets across every line.
// It is generated rather than configured in the dialplan because the plain
// _NXXNXXXXXX path never reaches doorman: a handset dialling a number talks to
// Asterisk and nothing else, which is exactly the property that keeps outbound
// calling working when doorman is down. A handset with no entry gets no
// set_var, and its endpoint is byte-identical to what it was before per-line
// identity existed.
func Build(handsets []policy.Handset, env Env, outbound map[string]OutboundIdentity) (*Fragments, error) {
	var problems []string
	fail := func(format string, args ...any) {
		problems = append(problems, fmt.Sprintf(format, args...))
	}

	var pjsip, plan strings.Builder
	pjsip.WriteString(header("handsets.toml", true))
	plan.WriteString(header("handsets.toml", false))
	plan.WriteString("[handsets-internal]\n")

	var all, pageMembers []string
	generated := 0

	for _, h := range handsets {
		// Pseudo-handsets (Local/600@internal and friends) are legitimate
		// policy targets but have no SIP registration to generate.
		if !strings.HasPrefix(h.Endpoint, "PJSIP/") {
			continue
		}
		resource := strings.TrimPrefix(h.Endpoint, "PJSIP/")
		if resource != h.ID {
			// We generate the endpoint named after the id; an endpoint that
			// disagrees would silently never match what policy dials.
			fail("handset %q endpoint %q must be PJSIP/%s (render names the endpoint after the id)", h.ID, h.Endpoint, h.ID)
			continue
		}
		if h.PasswordEnv == "" {
			fail("handset %q needs password_env (the .env variable holding its SIP password)", h.ID)
			continue
		}
		secret, ok := env(h.PasswordEnv)
		if !ok || secret == "" {
			fail("handset %q: %s is not set — add it to .env", h.ID, h.PasswordEnv)
			continue
		}

		label := h.Label
		if label == "" {
			label = h.ID
		}

		fmt.Fprintf(&pjsip, "; ── %s ──\n[%s]\n", label, h.ID)
		pjsip.WriteString("type=endpoint\ncontext=internal\ndisallow=all\nallow=ulaw\nallow=g722\n")
		fmt.Fprintf(&pjsip, "auth=%s-auth\naors=%s\n", h.ID, h.ID)
		pjsip.WriteString("direct_media=no\nforce_rport=yes\nrewrite_contact=yes\nrtp_symmetric=yes\ndtmf_mode=rfc4733\n")
		if h.Number > 0 {
			fmt.Fprintf(&pjsip, "callerid=%s <%d>\n", label, h.Number)
		} else {
			fmt.Fprintf(&pjsip, "callerid=%s\n", label)
		}
		if h.Mailbox != "" {
			fmt.Fprintf(&pjsip, "mailboxes=%s@household\n", h.Mailbox)
		}
		if out := outbound[h.ID]; out.set() {
			// Read by [cmm-outbound], the one context both outbound paths go
			// through, and deliberately NOT by _911: which trunk carries an
			// emergency call is a property of the house — the trunk whose
			// street address is registered — never of whichever line the
			// nearest handset happens to call as.
			if out.CID != "" {
				fmt.Fprintf(&pjsip, "set_var=%s=%s\n", outboundCIDVar, out.CID)
			}
			if out.Trunk != "" {
				fmt.Fprintf(&pjsip, "set_var=%s=%s\n", outboundTrunkVar, out.Trunk)
			}
		}
		fmt.Fprintf(&pjsip, "\n[%s-auth]\ntype=auth\nauth_type=userpass\nusername=%s\npassword=%s\n\n", h.ID, h.ID, secret)
		fmt.Fprintf(&pjsip, "[%s]\ntype=aor\nmax_contacts=2\nremove_existing=yes\nqualify_frequency=60\n\n", h.ID)
		generated++

		if h.Number > 0 {
			fmt.Fprintf(&plan, "exten => %d,1,Dial(%s,30)\n", h.Number, h.Endpoint)
			fmt.Fprintf(&plan, "exten => %d,hint,%s\n", h.Number, h.Endpoint)
		}
		all = append(all, h.Endpoint)
		if h.Page {
			pageMembers = append(pageMembers, h.Endpoint)
		}
	}

	if generated == 0 {
		fail("no PJSIP handsets to render")
	}
	if len(problems) > 0 {
		return nil, fmt.Errorf("render: %s", strings.Join(problems, "; "))
	}

	sort.Strings(all)
	sort.Strings(pageMembers)

	plan.WriteString("\n; Ring every handset.\n")
	fmt.Fprintf(&plan, "exten => 100,1,Dial(%s,30)\n", strings.Join(all, "&"))
	if len(pageMembers) > 0 {
		plan.WriteString("\n; Page: members auto-answer on speaker (page = true in handsets.toml).\n")
		fmt.Fprintf(&plan, "exten => 500,1,Page(%s,ib(page-autoanswer^s^1),60)\n",
			strings.Join(pageMembers, "&"))
	}

	return &Fragments{PJSIP: pjsip.String(), Dialplan: plan.String(), Generated: generated}, nil
}
