package provision

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"sort"
	"strings"
)

// The Grandstream dialect: one XML file, <gs_provision><config> holding
// P-values — every setting is a Pnnnn element. The skeleton and the file
// name fallbacks (cfg<mac>.xml, then cfg<model>.xml, then cfg.xml) are from
// Grandstream's SIP Device Provisioning Guide; the account P-values are
// consistent across the GXP/GRP/WP families. Each entry says what it pins
// and why, because the file is the phone-side half of invariants 9
// (RFC 2833) and 7's cousins, and a wrong number here fails the way this
// project hates most: silently.
//
// VERIFY marks values taken from family-wide convention rather than the
// WP8xx guide. The first rehearsal (a phone provisioned from this file, then
// its web UI read back) confirms or corrects each one; they are data.

type pvalue struct {
	p     int
	value string
	why   string
}

func grandstreamValues(p Phone) []pvalue {
	v := []pvalue{
		// Account 1 — the five fields typed by hand on 2026-09-21, never again.
		{271, "1", "account active"},
		{270, p.DisplayName(), "account name: the idle-screen label, room and number"},
		{47, p.Address.Host, "SIP server: this box"},
		{35, p.ID, "SIP user id"},
		{36, p.ID, "authenticate id"},
		{34, p.SIPPassword, "authenticate password"},
		{3, p.Label, "display name in From: what other phones see"},
		{33, VoicemailCode, "voicemail access number: the phone's voicemail key dials it"},

		// Nobody keeps the factory login.
		{2, p.AdminPassword, "web-admin password"},

		// DTMF: RFC 2833 only. The phone-side half of invariant 9 — without it
		// the lobby is deaf and every stranger is dismissed. VERIFY numbers.
		{73, "0", "DTMF in audio: off (VERIFY)"},
		{74, "1", "DTMF via RTP RFC 2833: on (VERIFY)"},
		{75, "0", "DTMF via SIP INFO: off (VERIFY)"},

		// Codecs, in the order Asterisk allows them: ulaw then g722.
		{57, "0", "vocoder 1: PCMU (VERIFY)"},
		{58, "9", "vocoder 2: G.722 (VERIFY)"},
		{59, "8", "vocoder 3: PCMA (VERIFY)"},

		// Clock. Schedules are local time, so a phone on UTC lies about bedtime.
		{30, "pool.ntp.org", "NTP server"},

		// Provisioning: where the phone fetches this very file from, over
		// HTTPS, presenting its own credential after first contact.
		{237, p.Address.ConfigServerPath(), "config server path"},
		{212, "2", "upgrade/provision via HTTPS (VERIFY)"},
		{1359, p.ID, "config server username (VERIFY)"},
		{1360, p.ProvisionPassword, "config server password (VERIFY)"},
		{194, "0", "automatic firmware upgrade: off"},

		// Directory: this phone's own book, polled on the phone's schedule.
		{330, p.Address.PhonebookPath(p.ID), "phonebook XML server path"},
		{331, "3", "phonebook download via HTTPS (VERIFY)"},
		{332, "60", "phonebook download interval, minutes"},
		{333, "0", "keep manually added entries"},
	}
	if tz := POSIXTimezone(p.Timezone); tz != "" {
		v = append(v, pvalue{246, tz, "self-defined time zone (POSIX) (VERIFY)"})
	}
	sort.Slice(v, func(i, j int) bool { return v[i].p < v[j].p })
	return v
}

func renderGrandstream(p Phone) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	fmt.Fprintf(&b, "<!-- GENERATED by \"doorman render\" from handsets.toml for %s (%s). DO NOT EDIT. Contains this phone's passwords. -->\n", p.ID, p.Model.ID)
	b.WriteString(`<gs_provision version="1">` + "\n")
	fmt.Fprintf(&b, "  <mac>%s</mac>\n", macNoColons(p.MAC))
	b.WriteString(`  <config version="1">` + "\n")
	for _, pv := range grandstreamValues(p) {
		fmt.Fprintf(&b, "    <P%d>", pv.p)
		if err := xml.EscapeText(&b, []byte(pv.value)); err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "</P%d><!-- %s -->\n", pv.p, xmlCommentSafe(pv.why))
	}
	b.WriteString("  </config>\n</gs_provision>\n")
	return b.Bytes(), nil
}

func macNoColons(mac string) string {
	out := make([]byte, 0, 12)
	for i := 0; i < len(mac); i++ {
		if mac[i] != ':' {
			out = append(out, mac[i])
		}
	}
	return string(out)
}

// "--" is illegal inside an XML comment.
func xmlCommentSafe(s string) string {
	return strings.ReplaceAll(s, "--", "- -")
}
